@startuml
class User {
    +id: int
    +username: String
    +password: String
    +email: String
}

class Transaction {
    +id: int
    +amount: float
    +description: String
    +date: Date
    +transactionType: TransactionType
    +categories: Category[]
    +account: Account
    +monthReference: Date
}

enum TransactionType {
    INCOME
    EXPENSE
}

class Category {
    +id: int
    +name: String
}

class CreditCard {
    +id: int
    +name: String
    +limit: float
    +invoices: Invoice[]
}

class Invoice {
    +id: int
    +amount: float
    +dueDate: Date
    +transactions: CreditCardTransaction[]
}

class Budget {
    +id: int
    +month: int
    +year: int
    +details: BudgetDetail[]
}

class BudgetDetail {
    +id: int
    +amount: float
    +category: Category
}

class Account {
    +id: int
    +name: String
    +balance: float
    +balanceSaved: float // Campo adicionado aqui
    +bank: Bank
}

class Bank {
    +id: int
    +name: String
}

class CashFlow {
    +id: int
    +amount: float
    +date: Date
    +source: String // Pode ser "Invoice" ou "Transaction"
    +account: Account
}

User "1" -- "0..*" Transaction
Transaction "0..*" -- "0..*" Category
Transaction "1" -- "1" Account
User "1" -- "0..*" CreditCard
CreditCard "1" -- "0..*" Invoice
Invoice "1" -- "0..*" Transaction
User "1" -- "0..*" Budget
Budget "1" -- "0..*" BudgetDetail
User "1" -- "0..*" Account
Account "1" -- "1" Bank

Invoice "0..*" -- "0..*" CashFlow : generates >
Transaction "0..*" -- "0..*" CashFlow : generates >
Account "1" -- "0..*" CashFlow : receives >
@enduml